### ISSUE TITLE
Array index out of range

### ISSUE THREAD

**Issue by Gurpartap** [cemolcay/ReorderableGridView-Swift#1]
I removed all the views but one. Then pressed + button. Result in screenshot:

![screen shot 2015-01-08 at 3 56 07 am](https://cloud.githubusercontent.com/assets/39792/5654564/51a06f28-96ea-11e4-8c6d-f7b758557120.png)

**Comment by cemolcay** [comment]
in the demo `addPressed:` function adds view to first column of second row (x: 0, y: 1)

```
func addPressed (sender: AnyObject) {
    gridView?.addReorderableView(itemView(), gridPosition: GridPosition (x: 0, y: 1))
}
```

it throws exception when your items array count less then `colsInRow`-1  
because second row doesn't exist in that case.

edit: i updated `addReordableView:gridPosition` function

```
func addReorderableView (view: ReorderableView, gridPosition: GridPosition) {
    super.addSubview(view)

    var addingIndex = gridPosition.arrayIndex(colsInRow!)
    if addingIndex >= reorderableViews.count {
        addingIndex = reorderableViews.count
    }

    reorderableViews.insert(view, atIndex: addingIndex)
    invalidateLayout()
}
```
